version: '3.8'

services:
  backend:
    image: quanghuy1604/ltm_be_image
    container_name: be_container
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:3306/ltm_demo
    ports:
      - 8080:8080

  frontend:
    image: quanghuy1604/ltm_fe_image
    container_name: fe_container
    depends_on:
      - backend
    ports:
      - 80:80

  tcpserver:
    image: tcpserver
    container_name: tcpserver_cnt
    depends_on:
      - database
    ports:
      - 807:807
    environment:
      - WEBHOOK_LOG_ENDPOINT=20.198.242.126:8080/api/webhook/log
      - WEBHOOK_SCOREBOARD_ENDPOINT=20.198.242.126:8080/api/webhook/scoreboard
      - JDBC_URL=jdbc:postgresql://database:5432/ltm_demo
      - JDBC_USERNAME = postgres
      - JDBC_PASSWORD = 1234

  database:
    image: postgres:14
    container_name: db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ltm_demo

volumes:
  postgres_data:
